baseURL = "https://hobikoding.com/"
title = "Hobi Koding â€” Mari Ngoding Sambil Tidur"
copyright = "Copyright (c) 2018, Hobikoding; all rights reserved."

languageCode = "id-id"
DefaultContentLanguage = "id"
theme = "hobikoding-theme"

enableRobotsTXT = true
enableEmoji = true
disqusShortname = "hobikode"
googleAnalytics = "UA-136352097-1"
paginate = 6
linenos=false

[author]
    name = "Saefulloh Maslul"
    email = "hobikoding@gmail.com"
    web = "https://hobikoding.com"

[params]
    description = "hobikoding - mari ngoding sambil tidur"
    SiteDescription = "Mari ngoding sambil tidur. Hobikode adalah blog yang akan membantumu belajar pemrograman dengan konten-konten berkualitas yang mudah dipahami"
    DefaultKeywords = "ReactJS, Node.js, React Native, JavaScript, Typescript"

[permalinks]
    posts = "/:slug"
    page = "/:slug"

[taxonomies]
    topic = "topic"

[outputs]
    home = ["JSON", "HTML", "RSS"]
    blog = ["JSON", "HTML", "RSS"]